// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package ums_permission

import (
	"database/sql"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/os/gtime"
)

// Entity is the golang structure for table ums_permission.
type Entity struct {
    Id         int64       `orm:"id,primary"  json:"id"`          //                                                      
    Pid        int64       `orm:"pid"         json:"pid"`         // 父级权限id                                           
    Name       string      `orm:"name"        json:"name"`        // 名称                                                 
    Value      string      `orm:"value"       json:"value"`       // 权限值                                               
    Icon       string      `orm:"icon"        json:"icon"`        // 图标                                                 
    Type       int         `orm:"type"        json:"type"`        // 权限类型：0->目录；1->菜单；2->按钮（接口绑定权限）  
    Uri        string      `orm:"uri"         json:"uri"`         // 前端资源路径                                         
    Status     int         `orm:"status"      json:"status"`      // 启用状态；0->禁用；1->启用                           
    CreateTime *gtime.Time `orm:"create_time" json:"create_time"` // 创建时间                                             
    Sort       int         `orm:"sort"        json:"sort"`        // 排序                                                 
}

// OmitEmpty sets OPTION_OMITEMPTY option for the model, which automatically filers
// the data and where attributes for empty values.
func (r *Entity) OmitEmpty() *arModel {
	return Model.Data(r).OmitEmpty()
}

// Inserts does "INSERT...INTO..." statement for inserting current object into table.
func (r *Entity) Insert() (result sql.Result, err error) {
	return Model.Data(r).Insert()
}

// InsertIgnore does "INSERT IGNORE INTO ..." statement for inserting current object into table.
func (r *Entity) InsertIgnore() (result sql.Result, err error) {
	return Model.Data(r).InsertIgnore()
}

// Replace does "REPLACE...INTO..." statement for inserting current object into table.
// If there's already another same record in the table (it checks using primary key or unique index),
// it deletes it and insert this one.
func (r *Entity) Replace() (result sql.Result, err error) {
	return Model.Data(r).Replace()
}

// Save does "INSERT...INTO..." statement for inserting/updating current object into table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
func (r *Entity) Save() (result sql.Result, err error) {
	return Model.Data(r).Save()
}

// Update does "UPDATE...WHERE..." statement for updating current object from table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
func (r *Entity) Update() (result sql.Result, err error) {
	return Model.Data(r).Where(gdb.GetWhereConditionOfStruct(r)).Update()
}

// Delete does "DELETE FROM...WHERE..." statement for deleting current object from table.
func (r *Entity) Delete() (result sql.Result, err error) {
	return Model.Where(gdb.GetWhereConditionOfStruct(r)).Delete()
}