// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package cms_prefrence_area

// Fill with you ideas below.