// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package pms_product_attribute_value

// Fill with you ideas below.