// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package ums_growth_change_history

// Fill with you ideas below.