// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package pms_product_full_reduction

// Fill with you ideas below.