// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package sms_flash_promotion_log

// Fill with you ideas below.