// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package oms_order_return_apply

// Fill with you ideas below.