// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package ums_member_product_category_relation

// Fill with you ideas below.