// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package oms_order

import (
	"database/sql"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/os/gtime"
)

// Entity is the golang structure for table oms_order.
type Entity struct {
    Id                    int64       `orm:"id,primary"              json:"id"`                      // 订单id                                                                        
    MemberId              int64       `orm:"member_id"               json:"member_id"`               //                                                                               
    CouponId              int64       `orm:"coupon_id"               json:"coupon_id"`               //                                                                               
    OrderSn               string      `orm:"order_sn"                json:"order_sn"`                // 订单编号                                                                      
    CreateTime            *gtime.Time `orm:"create_time"             json:"create_time"`             // 提交时间                                                                      
    MemberUsername        string      `orm:"member_username"         json:"member_username"`         // 用户帐号                                                                      
    TotalAmount           float64     `orm:"total_amount"            json:"total_amount"`            // 订单总金额                                                                    
    PayAmount             float64     `orm:"pay_amount"              json:"pay_amount"`              // 应付金额（实际支付金额）                                                      
    FreightAmount         float64     `orm:"freight_amount"          json:"freight_amount"`          // 运费金额                                                                      
    PromotionAmount       float64     `orm:"promotion_amount"        json:"promotion_amount"`        // 促销优化金额（促销价、满减、阶梯价）                                          
    IntegrationAmount     float64     `orm:"integration_amount"      json:"integration_amount"`      // 积分抵扣金额                                                                  
    CouponAmount          float64     `orm:"coupon_amount"           json:"coupon_amount"`           // 优惠券抵扣金额                                                                
    DiscountAmount        float64     `orm:"discount_amount"         json:"discount_amount"`         // 管理员后台调整订单使用的折扣金额                                              
    PayType               int         `orm:"pay_type"                json:"pay_type"`                // 支付方式：0->未支付；1->支付宝；2->微信                                       
    SourceType            int         `orm:"source_type"             json:"source_type"`             // 订单来源：0->PC订单；1->app订单                                               
    Status                int         `orm:"status"                  json:"status"`                  // 订单状态：0->待付款；1->待发货；2->已发货；3->已完成；4->已关闭；5->无效订单  
    OrderType             int         `orm:"order_type"              json:"order_type"`              // 订单类型：0->正常订单；1->秒杀订单                                            
    DeliveryCompany       string      `orm:"delivery_company"        json:"delivery_company"`        // 物流公司(配送方式)                                                            
    DeliverySn            string      `orm:"delivery_sn"             json:"delivery_sn"`             // 物流单号                                                                      
    AutoConfirmDay        int         `orm:"auto_confirm_day"        json:"auto_confirm_day"`        // 自动确认时间（天）                                                            
    Integration           int         `orm:"integration"             json:"integration"`             // 可以获得的积分                                                                
    Growth                int         `orm:"growth"                  json:"growth"`                  // 可以活动的成长值                                                              
    PromotionInfo         string      `orm:"promotion_info"          json:"promotion_info"`          // 活动信息                                                                      
    BillType              int         `orm:"bill_type"               json:"bill_type"`               // 发票类型：0->不开发票；1->电子发票；2->纸质发票                               
    BillHeader            string      `orm:"bill_header"             json:"bill_header"`             // 发票抬头                                                                      
    BillContent           string      `orm:"bill_content"            json:"bill_content"`            // 发票内容                                                                      
    BillReceiverPhone     string      `orm:"bill_receiver_phone"     json:"bill_receiver_phone"`     // 收票人电话                                                                    
    BillReceiverEmail     string      `orm:"bill_receiver_email"     json:"bill_receiver_email"`     // 收票人邮箱                                                                    
    ReceiverName          string      `orm:"receiver_name"           json:"receiver_name"`           // 收货人姓名                                                                    
    ReceiverPhone         string      `orm:"receiver_phone"          json:"receiver_phone"`          // 收货人电话                                                                    
    ReceiverPostCode      string      `orm:"receiver_post_code"      json:"receiver_post_code"`      // 收货人邮编                                                                    
    ReceiverProvince      string      `orm:"receiver_province"       json:"receiver_province"`       // 省份/直辖市                                                                   
    ReceiverCity          string      `orm:"receiver_city"           json:"receiver_city"`           // 城市                                                                          
    ReceiverRegion        string      `orm:"receiver_region"         json:"receiver_region"`         // 区                                                                            
    ReceiverDetailAddress string      `orm:"receiver_detail_address" json:"receiver_detail_address"` // 详细地址                                                                      
    Note                  string      `orm:"note"                    json:"note"`                    // 订单备注                                                                      
    ConfirmStatus         int         `orm:"confirm_status"          json:"confirm_status"`          // 确认收货状态：0->未确认；1->已确认                                            
    DeleteStatus          int         `orm:"delete_status"           json:"delete_status"`           // 删除状态：0->未删除；1->已删除                                                
    UseIntegration        int         `orm:"use_integration"         json:"use_integration"`         // 下单时使用的积分                                                              
    PaymentTime           *gtime.Time `orm:"payment_time"            json:"payment_time"`            // 支付时间                                                                      
    DeliveryTime          *gtime.Time `orm:"delivery_time"           json:"delivery_time"`           // 发货时间                                                                      
    ReceiveTime           *gtime.Time `orm:"receive_time"            json:"receive_time"`            // 确认收货时间                                                                  
    CommentTime           *gtime.Time `orm:"comment_time"            json:"comment_time"`            // 评价时间                                                                      
    ModifyTime            *gtime.Time `orm:"modify_time"             json:"modify_time"`             // 修改时间                                                                      
}

// OmitEmpty sets OPTION_OMITEMPTY option for the model, which automatically filers
// the data and where attributes for empty values.
func (r *Entity) OmitEmpty() *arModel {
	return Model.Data(r).OmitEmpty()
}

// Inserts does "INSERT...INTO..." statement for inserting current object into table.
func (r *Entity) Insert() (result sql.Result, err error) {
	return Model.Data(r).Insert()
}

// InsertIgnore does "INSERT IGNORE INTO ..." statement for inserting current object into table.
func (r *Entity) InsertIgnore() (result sql.Result, err error) {
	return Model.Data(r).InsertIgnore()
}

// Replace does "REPLACE...INTO..." statement for inserting current object into table.
// If there's already another same record in the table (it checks using primary key or unique index),
// it deletes it and insert this one.
func (r *Entity) Replace() (result sql.Result, err error) {
	return Model.Data(r).Replace()
}

// Save does "INSERT...INTO..." statement for inserting/updating current object into table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
func (r *Entity) Save() (result sql.Result, err error) {
	return Model.Data(r).Save()
}

// Update does "UPDATE...WHERE..." statement for updating current object from table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
func (r *Entity) Update() (result sql.Result, err error) {
	return Model.Data(r).Where(gdb.GetWhereConditionOfStruct(r)).Update()
}

// Delete does "DELETE FROM...WHERE..." statement for deleting current object from table.
func (r *Entity) Delete() (result sql.Result, err error) {
	return Model.Where(gdb.GetWhereConditionOfStruct(r)).Delete()
}